name: ci

on:
  push:

jobs:
  image:
    runs-on: artsiom-runner-set
    steps:
      - uses: actions/checkout@v4
      
      - run: |
          apt-get update && apt-get install -y netcat
          nc -vz buildkit.arc-systems.svc.cluster.local 1234

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: tcp://buildkit.arc-systems.svc.cluster.local:1234
          driver: remote

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: docker.io/kirtanus/gcp_kube_workspace:2.8
