name: Debug
on:
  pull_request:
    branches: [ main ]

jobs:
  test-deploy:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          kind create cluster
          helm repo add kyverno https://kyverno.github.io/kyverno/
          helm install kyverno --namespace kyverno kyverno/kyverno --create-namespace --wait --timeout 2m

      - name: Debug Info
        if: ${{ failure() }}
        shell: bash {0}
        run: |
          kubectl get all -A
