name: Debug
on:
  pull_request:
    branches: [ main ]

jobs:
  test-deploy:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          kind create cluster
          helm repo add kyverno https://kyverno.github.io/kyverno/
          helm install kyverno --namespace kyverno kyverno/kyverno --create-namespace --wait --timeout 1m --set cleanupController.enabled=false

      - name: Debug Info
        if: ${{ failure() }}
        shell: bash {0}
        run: |
          kubectl get all -A
          podname=$(kubectl get pod -n kyverno --no-headers -o custom-columns=":metadata.name")
          kubectl logs -n kyverno $podname --all-containers=true

